### ISSUE TITLE
add autostart list command

### ISSUE THREAD

**Issue by vshymanskyy** [maxrimue/node-autostart#43]
just display a table of configured autostart commands

thx!

**Comment by maxrimue** [comment]
Do you think the command should display all autostart items on your system or just the ones that were enabled through node-autostart? Thanks!

**Comment by vshymanskyy** [comment]
Just node-autostart, I think!

**Comment by maxrimue** [comment]
@vshymanskyy The reason I was asking is that if this command should just display select autostart items, so the ones node-autostart manages, there would have to be a file where information is stored about which autostart service belongs to node-autostart and which doesn't. That means you'd have to re-enable all of them for the list command to work. By showing simply all autostart items, this wouldn't be necessary.

Note that "autostart items" will most likely not include eg apps that start when you boot your device, but rather just scripts you configured yourself, so it wouldn't be that much. Do you still think we should just show node-autostart items despite all of this? I'm honestly not sure.

**Comment by maxrimue** [comment]
Due to tight resources and serious issues with this project, I'm deprecating it. I highly recommend [auto-launch](https://www.npmjs.com/package/auto-launch), it has a similar API and should be easy to switch over to. Sorry for the circumstances.
