### ISSUE TITLE
OS compatability/tested list?

### ISSUE THREAD

**Issue by wumke** [maxrimue/node-autostart#84]
Firstly, I 'd like to say that I'm a big fan of this kind of projects!

I saw that you use a cronjob on linux with @reboot, I know there were some issues with that on various systems and versions of crontab... So my question is do you have a list of OS versions this library works with? (windows, mac, linux)

If so, add it to your readme.

**Comment by maxrimue** [comment]
Hey @wumke, as the readme indicates, this project supports Linux, Windows and macOS. I've seen the errors travis was getting with crontab, but I'm honestly not sure what's causing it. Running tests and even manually trying this module on my Linux Mint machine works just as always, so there might be something wrong with this module running on travis in particular (which doesn't look like a huge problem, but I'd like to find out what's causing it anyway).

If you have any idea what's causing it, you're welcome to contribute!

**Comment by maxrimue** [comment]
Okay, I think I found the issue and am working on a fix, hoping to be able to push and publish in the next few days. It turns out it really only was an issue with travis, on regular PCs the module still worked well.

**Comment by maxrimue** [comment]
Due to tight resources and serious issues with this project, I'm deprecating it. I highly recommend [auto-launch](https://www.npmjs.com/package/auto-launch), it has a similar API and should be easy to switch over to. Sorry for the circumstances.
