### ISSUE TITLE
MacOS startup issue when running as root.

### ISSUE THREAD

**Issue by f-prime** [maxrimue/node-autostart#86]
First off, thanks so much for creating this library. It is helping me out big time, but I seem to be an edge case. I need to run my node application as root. When I try to create the startup file on MacOS the framework attempts to put the file into  `/Users/root/Library/LaunchAgents/` which does not exist. I have the code locally and have made the change to allow for the specifying of the username, but I figured I'd let you know anyway since this is an issue.

**Comment by maxrimue** [comment]
Ah yeah I see, thanks for letting me know! Do you want to submit your changes via a pr? If not, I'll give it a try soon

**Comment by f-prime** [comment]
I'll have time over the weekend to make a pull request. The issue also seems to exist on Windows.

**Comment by maxrimue** [comment]
Due to tight resources and serious issues with this project, I'm deprecating it. I highly recommend [auto-launch](https://www.npmjs.com/package/auto-launch), it has a similar API and should be easy to switch over to. Sorry for the circumstances.
