### ISSUE TITLE
add autostart run once

### ISSUE THREAD

**Issue by michapixel** [maxrimue/node-autostart#89]
Would be helpful if the cli would ask $user if he'd like to run the command, after it's added. Or simply do it ;)

**Comment by maxrimue** [comment]
I'm not sure if this approach would be making sense for the majority of users of this module, especially since implementing this extra step on your own in your code shouldn't be too complicated (_correct me if I'm wrong_). Glad to further discuss this

**Comment by maxrimue** [comment]
Due to tight resources and serious issues with this project, I'm deprecating it. I highly recommend [auto-launch](https://www.npmjs.com/package/auto-launch), it has a similar API and should be easy to switch over to. Sorry for the circumstances.
