### ISSUE TITLE
How i can see list app for autostart from node?

### ISSUE THREAD

**Issue by kksudo** [maxrimue/node-autostart#92]

**Comment by kksudo** [comment]
if it is linux you can see all jobs in crontab , like this:
`crontab -e`

**Comment by daniyel** [comment]
it would be nice something like `autostart list`

in https://github.com/maxrimue/node-autostart/blob/master/lib/darwin.js

For OSX you could save app with "prefix" `com.nodeautostart.<key>` under `/Users/<user>/Library/LaunchAgents/` and then you could use something like `find -E /Users/<user>/Library/LaunchAgents/ -iregex '.*(com\.nodeautostart\..*)' | sed 's/.*\///'` to list the apps that were added with autostart

**Comment by maxrimue** [comment]
Sorry for tuning in so late. I find the idea interesting, what‘s holding me back is backwards compatability for already enabled services, as those would not be listed.

**Comment by maxrimue** [comment]
Due to tight resources and serious issues with this project, I'm deprecating it. I highly recommend [auto-launch](https://www.npmjs.com/package/auto-launch), it has a similar API and should be easy to switch over to. Sorry for the circumstances.
